# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f57f0c2304c4c1221e503706959658bffb2e5039679452a4cdf2bc875d5b7db9d4f0f669ebb558c746c3fb446e34dd9e972a111eabc372b0428a9a5123fa713a

test:
  secret_key_base: de6a860a48fa063a73bfcd4b10a5e22cbf02a6cfe1e92b0d939e1f819d33c55663bad044c930df5d3561f8d739c54c0abd271739a5059b2848dfeddca2b8c811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
